### ISSUE TITLE
Custom NTP server role

### ISSUE THREAD

**Issue by pauljarvis** [OurFriendIrony/ansible#27]
The corporate network doesn't connect to the various publicly available time servers as port 123 is blocked.  There is an on-prem time server which can be configured to ensure system time is kept in sync.  It would be nice to have a role in the ansible which allows you to specify a particular server to use.

Changes required:
```
$ sudo cat /etc/systemd/timesyncd.conf 
[Time]
NTP={insert_server_here}
```
Restart the timesync service.
```
$ sudo systemctl restart systemd-timesyncd
```

**Comment by OurFriendIrony** [comment]
Not doing. Submit a PR if still required
